name: Version Check

on:
  push:
    branches:
      - homolog
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - homolog

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check package version
        uses: gfellerph/package-json-version-check@v1.0.0-alpha.2
        id: version-check
        with:
          path: package.json

      - name: Echo result
        run: echo "Version updated"
        
  check-manifest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: homolog

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master

      - name: Compare manifest versions
        run: |
          PR_VERSION=$(jq -r .version pr-branch/src/manifest.json)
          BASE_VERSION=$(jq -r .version base-branch/src/manifest.json)
          echo "PR version: $PR_VERSION"
          echo "Base version: $BASE_VERSION"
          if [ "$PR_VERSION" = "$BASE_VERSION" ]; then
            echo "❌ Manifest version not updated!"
            exit 1
          else
            echo "✅ Manifest version updated."
          fi
